spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}  # Usa 8080 por defecto si no está definida