spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: A123456
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: never

server:
  port: 8080