-- =========================================================
-- CREACIÓN DE TABLESPACES
-- =========================================================

CREATE TABLESPACE TBS_USUARIOS
DATAFILE '/opt/oracle/oradata/tbs_usuarios01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE TBS_PLAN_ESTUDIO
DATAFILE '/opt/oracle/oradata/tbs_plan_estudio01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE TBS_CURSO
DATAFILE '/opt/oracle/oradata/tbs_curso01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE TBS_EVALUACION
DATAFILE '/opt/oracle/oradata/tbs_evaluacion01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 20M MAXSIZE 1G;

CREATE TABLESPACE TBS_BANCO_PREGUNTAS
DATAFILE '/opt/oracle/oradata/tbs_banco_preguntas01.dbf'
SIZE 150M
AUTOEXTEND ON NEXT 25M MAXSIZE 2G;


-- =========================================================
-- MIGRACIÓN DE TABLAS A CADA TABLESPACE
-- =========================================================

-- 🧑‍💻 TBS_USUARIOS
ALTER TABLE usuario MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE rol MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE usuario_rol MOVE TABLESPACE TBS_USUARIOS;
ALTER TABLE token MOVE TABLESPACE TBS_USUARIOS;

-- 📚 TBS_PLAN_ESTUDIO
ALTER TABLE plan_estudio MOVE TABLESPACE TBS_PLAN_ESTUDIO;
ALTER TABLE unidad MOVE TABLESPACE TBS_PLAN_ESTUDIO;
ALTER TABLE contenido MOVE TABLESPACE TBS_PLAN_ESTUDIO;
ALTER TABLE tema MOVE TABLESPACE TBS_PLAN_ESTUDIO;

-- 🏫 TBS_CURSO
ALTER TABLE curso MOVE TABLESPACE TBS_CURSO;
ALTER TABLE curso_estudiante MOVE TABLESPACE TBS_CURSO;

-- 📝 TBS_EVALUACION
ALTER TABLE evaluacion MOVE TABLESPACE TBS_EVALUACION;
ALTER TABLE evaluacion_pregunta MOVE TABLESPACE TBS_EVALUACION;
ALTER TABLE evaluacion_curso MOVE TABLESPACE TBS_EVALUACION;
ALTER TABLE evaluacion_estudiante MOVE TABLESPACE TBS_EVALUACION;
ALTER TABLE estado_evaluacion MOVE TABLESPACE TBS_EVALUACION;
ALTER TABLE tipo_seleccion MOVE TABLESPACE TBS_EVALUACION;
ALTER TABLE estado_evaluacion_estudiante MOVE TABLESPACE TBS_EVALUACION;

-- ❓ TBS_BANCO_PREGUNTAS
ALTER TABLE tipo_pregunta MOVE TABLESPACE TBS_BANCO_PREGUNTAS;
ALTER TABLE banco_preguntas MOVE TABLESPACE TBS_BANCO_PREGUNTAS;
ALTER TABLE opcion_respuesta MOVE TABLESPACE TBS_BANCO_PREGUNTAS;
ALTER TABLE sub_pregunta MOVE TABLESPACE TBS_BANCO_PREGUNTAS;
ALTER TABLE respuesta_correcta MOVE TABLESPACE TBS_BANCO_PREGUNTAS;
ALTER TABLE respuesta_estudiante MOVE TABLESPACE TBS_BANCO_PREGUNTAS;


-- =========================================================
-- RECONSTRUCCIÓN DE ÍNDICES EN SU NUEVO TABLESPACE
-- =========================================================
-- =========================================================
-- RECONSTRUCCIÓN AUTOMÁTICA DE ÍNDICES VÁLIDOS
-- =========================================================
BEGIN
  FOR idx IN (
    SELECT index_name
    FROM user_indexes
    WHERE index_type = 'NORMAL'
    AND table_name IN (
      'USUARIO', 'ROL', 'USUARIO_ROL', 'TOKEN',
      'PLAN_ESTUDIO', 'UNIDAD', 'CONTENIDO', 'TEMA',
      'CURSO', 'CURSO_ESTUDIANTE',
      'EVALUACION', 'EVALUACION_PREGUNTA', 'EVALUACION_CURSO', 'EVALUACION_ESTUDIANTE',
      'ESTADO_EVALUACION', 'TIPO_SELECCION', 'ESTADO_EVALUACION_ESTUDIANTE',
      'TIPO_PREGUNTA', 'BANCO_PREGUNTAS', 'OPCION_RESPUESTA',
      'SUB_PREGUNTA', 'RESPUESTA_CORRECTA', 'RESPUESTA_ESTUDIANTE'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER INDEX ' || idx.index_name || ' REBUILD';
  END LOOP;
END;
/